PACKAGE_NAME="nouveau-hpd-ddc"
PACKAGE_VERSION="0.1.6"
AUTOINSTALL="yes"

BUILT_MODULE_NAME[0]="nouveau"
BUILT_MODULE_LOCATION[0]="output"
DEST_MODULE_LOCATION[0]="/updates/dkms"

MAKE[0]="bash ./dkms-build.sh ${kernelver}"
CLEAN="bash ./dkms-clean.sh"
POST_INSTALL="./dkms-post-install.sh ${kernelver}"
POST_REMOVE="./dkms-post-remove.sh ${kernelver}"
